### PR TITLE
Add polish translations

### PR DESCRIPTION
**Pull request by azranel**
So those are only files with Polish translations, that's all. :smile: Didn't see any and since Im native speaker then I thought I could at least contribute in that way :smile:

### CODE REVIEW

**Comment by mamhoff** [comment]
That's amazing! Thank you!

**Comment by robinboening** [comment]
Yeah! Thank you very much @azranel, its really great to see AlchemyCMS getting more more internationalized.

**Comment by robinboening** [comment]
@azranel maaaaaybe you want to provide a translation for Alchemy core as well? https://github.com/AlchemyCMS/alchemy_cms/tree/master/config/locales That would be super awesome! :heart:

**Comment by azranel** [comment]
@robinboening sure, no problem :smile: It will take more yet after all since there are a lot more translations :)

**Comment by tvdeyen** [comment]
Very much appreciated. I will fix the build ASAP. 
Thanks!

**Comment by tvdeyen** [comment]
@azranel fix is in current master. Please rebase your branch. Thanks

**Comment by azranel** [comment]
Looks ready for :shipit: :smile:

**Comment by tvdeyen** [comment]
Podziękowania

**Pull request merged**
