### PR TITLE
Allow setting a layout for user_sessions and passwords controller

### PR DESCRIPTION
**Pull request by robinboening**
A layout can be set using an initializer in the host app.

```
Alchemy::Devise.layout = "login"
```

The fallback value ensures backwards compatibility.

### CODE REVIEW

**Comment by robinboening** [comment]
@tvdeyen any idea why none of the ruby versions is found in CI?

**Comment by tvdeyen** [comment]
We are using a widely used GitHub action here. Not sure what's happening. Retrying

**Comment by tvdeyen** [comment]
@robinboening please rebase with latest `main`. This should fix the CI

**Review by tvdeyen — APPROVED** [review]

**Comment by tvdeyen** [comment]
@robinboening "Was lange währt, wird endlich gut" :)

 https://github.com/AlchemyCMS/alchemy-devise/releases/tag/v7.1.2

**Pull request merged**
